CREATE TABLE [ToDo].[ListItem]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	[IsComplete] BIT NOT NULL DEFAULT(0),
	[Content] NVARCHAR(256) NOT NULL,
	[CreatedOn] DATETIME2 NOT NULL DEFAULT(GETDATE()),
	[UpdatedOn] DATETIME2 NOT NULL DEFAULT(GETDATE())
)
